export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES'
export const LOAD_ALL_ARTICLES_START = 'LOAD_ALL_ARTICLES_START'
export const LOAD_ALL_ARTICLES_SUCCESS = 'LOAD_ALL_ARTICLES_SUCCESS'
export const LOAD_ALL_ARTICLES_FAIL = 'LOAD_ALL_ARTICLES_FAIL'


export const ADD_COMMENT = 'ADD_COMMENT'